version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
<<<<<<< HEAD
      - DB_HOST=localhost
=======
      - DB_HOST=localhost:3306
>>>>>>> 55eb451f0c5f5b285751e47956ed76e144350cea
      - DB_USER=root
      - DB_PASSWORD=1016945145
      - DB_NAME=railway
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1016945145
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"
