version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=1016945145
      - DB_NAME=database
      - DB_PORT=3306
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: TGmIksAkBTBPQxmNPhPsDdlUfBIGAsEk
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"