version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost:3306
      - DB_USER=root
      - DB_PASSWORD=1016945145
      - DB_NAME=database
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1016945145
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
