version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:TGmIksAkBTBPQxmNPhPsDdlUfBIGAsEk@hopper.proxy.rlwy.net:10204/railway
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: TGmIksAkBTBPQxmNPhPsDdlUfBIGAsEk
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"